### ISSUE TITLE
Android build error in ionic capacitor

### ISSUE THREAD

**Issue by Kaoschuks** [gurisko/cordova-plugin-accountkit#59]
Whenever i build my ionic capacitor app for android i get

E/AccountKitPlugin: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
        at 
android.support.v4.app.BaseFragmentActivityApi14.checkForValidRequestCode(BaseFragmentActivityApi14.java:79)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:748)
        at org.apache.cordova.CordovaInterfaceImpl.startActivityForResult(CordovaInterfaceImpl.java:68)
        at org.apache.cordova.facebook.AccountKitPlugin.executeLogin(AccountKitPlugin.java:136)
        at org.apache.cordova.facebook.AccountKitPlugin$1.run(AccountKitPlugin.java:56)

**Comment by Kaoschuks** [comment]
I need an answer on this please can anybody from the accountkit team help

**Comment by jcesarmobile** [comment]
You have to change this number to be a bit smaller https://github.com/gurisko/cordova-plugin-accountkit/blob/master/src/android/AccountKitPlugin.java#L31

**Comment by Kaoschuks** [comment]
I have reduced it to 65530 but it didn't work.

Please try and fix it please if possible please

**Comment by Kaoschuks** [comment]
I fixed it for android works wonderfully

**Comment by jcesarmobile** [comment]
Linking PR https://github.com/gurisko/cordova-plugin-accountkit/pull/64

**Comment by Kaoschuks** [comment]
Thanks
    On Wednesday, June 26, 2019, 02:09:23 PM GMT+1, jcesarmobile <notifications@github.com> wrote:  
 
 
Linking PR #64
